
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bidiifadyjjnwvwiutgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZGlpZmFkeWpqbnd2d2l1dGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTgwMjAsImV4cCI6MjA1OTYzNDAyMH0.k6rz6hgxlOJ6yVC6rW1GKZ6ZSh-NVxTixssXWNk4RvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
